model_opts:
  name: "UnetDropout"
  args:
    inchannels: 17
    outchannels: 2
    net_depth: 5
    dropout: 0.2
    spatial: True
optim_opts:
  name: "Adam"
  args:
    lr: 0.0001
metrics_opts:
  IoU:
    threshold: 0.4
  pixel_acc:
    threshold: 0.4
  precision:
    threshold: 0.4
  recall:
    threshold: 0.4
  dice:
    threshold: 0.4
  f1_score:
    threshold: 0.4
  f2_score:
    threshold: 0.4
log_opts:
  mask_names: ["Glacial Lake", "Background"]
  reg_opts:
    l2_reg: 0.0005